### ISSUE TITLE
Create the Navbar Component

### ISSUE THREAD

**Issue by kahoragachau** [TrivOrg/Triv#1]
**User Stories**
---
As a user I want to be able to see a navbar at the top of the page

**Description**
---
As a user I will use the navbar to and the navbar items to quickly move inside the site faster and or being redirected to a new page, by clicking the navbar item eg about

![Image](https://github.com/TrivOrg/Triv/assets/99868443/099175e1-f5d9-45f3-ac0d-260e8419738c)

**Acceptance Criteria**

- Should Be pixel perfect like the design above
- Lines of code should not be more than 100 Lines of code
- Should Only display, Triv Text Logo, Home, About, Contacts and a Sign Up Button.

**Comment by yr1404** [comment]
If the issue is open, I would like to work on it.

**Comment by kahoragachau** [comment]
@yr1404 I'm Working on it, You can work on issue #4

**Comment by yr1404** [comment]
Okay @kahoragachau
