### ISSUE TITLE
Create the About Section

### ISSUE THREAD

**Issue by kahoragachau** [TrivOrg/Triv#3]
### **User Stories**
---
As a user I want to be able to see a section with a title of about 

### **Description**
---
As a user I will see a header with the name "About", inside this section it will contain three rows that will have a paragraph of text and an image with the position of the paragraphs and images appearing in either position right or left.
![image](https://github.com/TrivOrg/Triv/assets/99868443/1f392136-3454-434e-8988-38a98481bb6c)

**Acceptance Criteria**

- Should be pixel perfect  like the design above
- Lines of code should not be more than 100 lines of code
- Should be below the hero section, Should display three paragraphs of text and three images.

**Comment by yr1404** [comment]
I'd like to work on this issue.

**Comment by kahoragachau** [comment]
go for it @yr1404

**Comment by yr1404** [comment]
Can you assign it to me?

**Comment by kahoragachau** [comment]
@yr1404 I've assigned it to you

**Comment by yr1404** [comment]
#7 Done
