### ISSUE TITLE
Create the contacts Section

### ISSUE THREAD

**Issue by kahoragachau** [TrivOrg/Triv#4]
### **User Stories**
---
As a user I want to be able to see your contact Information
### **Description**
---
As a user I will be able to see your social profilesi.e linkedin, twitter etc, I will be able to see where term and condition are located, the FAQs link, Documentation and blogs. There will be three rows, The contact row, the Company's section and  the resource row.
![image](https://github.com/TrivOrg/Triv/assets/99868443/88d93781-062e-4a21-9058-409ce11700db)

**Acceptance criteria**
---

- Should be pixel perfect as the design above.
- lines of code should not be more than 100 .
- Should display three rows, namely "Our Socials", "Resources" and "Company"

**Comment by Samarth-Dengre** [comment]
This section will be part of the footer?

**Comment by vaibhav384** [comment]
I can try this, Assign this to me.
